### ISSUE TITLE
Add limit to soql queries

### ISSUE THREAD

**Issue by Mercer44** [ForceDotComLabs/cloud-swarm#5]
Our organization is running this error when trying to automatically create chatter posts based on record changes. In the feedPostSwarm.trigger, the soql query needs to have a 'limit 999' added at the end. This 'limit' addition should most likely be added other places as well. 
Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, XTrigger: execution of BeforeInsert caused by: ConnectApi.ConnectApiException: cloudswarm.feedPostSwarm: execution of AfterInsert caused by: System.QueryException: Implementation restriction: EntitySubscription only allows security evaluation for non-admin users when LIMIT is specified and at most 1000 (cloudswarm)

**Comment by sfckemp** [comment]
I've added your fix, updated SwarmHelper.cls with similar fixes, and will update the AppExchange packages shortly.

Thanks for your contribution, Mercer44!  It is very much appreciated and makes Cloud Swarm better for everyone.
