### ISSUE TITLE
Add limit to soql queries

### ISSUE THREAD

**Issue by vibindavis** [ForceDotComLabs/cloud-swarm#7]
Hi,

We are facing the below error mentioned in the below Issue:
https://github.com/ForceDotComLabs/cloud-swarm/issues/5

Insert failed. First exception on row 0; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, cloudswarm.feedPostSwarm: execution of AfterInsert caused by: System.QueryException: Implementation restriction: EntitySubscription only allows security evaluation for non-admin users when LIMIT is specified and at most 1000 Trigger.cloudswarm.feedPostSwarm: line 50, column 1

We are using version 3.1

Thanks in advance.

**Comment by sfckemp** [comment]
This has been fixed and pushed to the AppExchange package.  Please update your AppExchange package to the latest version.
